services:
  app:
    build: .
    container_name: restaurantmanager
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - app_data:/data
    restart: unless-stopped

volumes:
  app_data:



